#!/usr/bin/env python3
"""
Jarvis Setup Wizard — HTTP Server
Stdlib only. No external dependencies.
Serves the wizard UI and handles config write + completion.
"""

import http.server
import json
import os
import pathlib
import platform
import re
import secrets
import sys
import threading
import urllib.parse
from http import HTTPStatus

# ── Paths ────────────────────────────────────────────────────────
SCRIPT_DIR = pathlib.Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent  # usb-product/
HOME = pathlib.Path.home()

WORKSPACE = HOME / "jarvis-workspace"
if platform.system() == "Windows":
    WORKSPACE = pathlib.Path("C:/Jarvis")

OPENCLAW_DIR = HOME / ".openclaw"
TEMPLATE_PATH = PROJECT_ROOT / "openclaw-template.json"
WIZARD_HTML = SCRIPT_DIR / "index.html"
COMPLETE_FLAG = WORKSPACE / ".setup-complete"

PORT = 9999

# Current status (read by GET /api/status)
_status = {"step": "collecting_keys", "message": "Waiting for configuration"}
_status_lock = threading.Lock()


def set_status(step: str, message: str):
    with _status_lock:
        _status["step"] = step
        _status["message"] = message


def get_status() -> dict:
    with _status_lock:
        return dict(_status)


# ── Config Writers ───────────────────────────────────────────────
def write_env_file(config: dict) -> pathlib.Path:
    """Write ~/jarvis-workspace/builder/.env"""
    env_dir = WORKSPACE / "builder"
    env_dir.mkdir(parents=True, exist_ok=True)
    env_path = env_dir / ".env"

    lines = [
        "# Jarvis — environment config",
        "# Generated by Jarvis Setup Wizard",
        "",
        f"ANTHROPIC_API_KEY={config.get('anthropicKey', '')}",
        f"GOOGLE_PLACES_API_KEY={config.get('googleKey', '')}",
        f"PERPLEXITY_API_KEY={config.get('perplexityKey', '')}",
        "",
        f"BUSINESS_NAME={config.get('businessName', '')}",
        f"BUSINESS_INDUSTRY={config.get('industry', '')}",
        f"BUSINESS_PHONE={config.get('phone', '')}",
        f"BUSINESS_EMAIL={config.get('email', '')}",
        f"BUSINESS_WEBSITE={config.get('website', '')}",
        "",
        "JARVIS_PORT=8080",
        "OPENCLAW_GATEWAY_PORT=18789",
    ]

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_path


def write_openclaw_config(config: dict) -> pathlib.Path:
    """Write ~/.openclaw/openclaw.json from template."""
    OPENCLAW_DIR.mkdir(parents=True, exist_ok=True)
    config_path = OPENCLAW_DIR / "openclaw.json"

    if TEMPLATE_PATH.exists():
        template = TEMPLATE_PATH.read_text(encoding="utf-8")
    else:
        # Fallback minimal template if USB template is missing
        template = json.dumps({
            "models": {
                "mode": "merge",
                "providers": {
                    "anthropic": {
                        "baseUrl": "https://api.anthropic.com/v1",
                        "apiKey": "__ANTHROPIC_API_KEY__",
                        "auth": "api-key",
                        "api": "anthropic-messages",
                        "models": [
                            {
                                "id": "claude-sonnet-4-5",
                                "name": "Claude Sonnet 4.5",
                                "reasoning": False,
                                "input": ["text"],
                                "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
                                "contextWindow": 200000,
                                "maxTokens": 8192
                            }
                        ]
                    }
                }
            },
            "agents": {
                "defaults": {
                    "model": {
                        "primary": "anthropic/claude-sonnet-4-5",
                        "fallbacks": ["anthropic/claude-haiku-4-5-20251001"]
                    },
                    "workspace": "__WORKSPACE_PATH__",
                    "contextPruning": {"mode": "cache-ttl", "ttl": "1h"},
                    "compaction": {"mode": "safeguard"},
                    "heartbeat": {"every": "30m"}
                }
            },
            "gateway": {
                "port": 18789,
                "mode": "local",
                "bind": "loopback",
                "auth": {"mode": "token", "token": "__GATEWAY_TOKEN__"}
            }
        }, indent=2)

    # Fill in placeholders
    gateway_token = secrets.token_hex(32)
    workspace_str = str(WORKSPACE).replace("\\", "/")

    filled = (
        template
        .replace("__ANTHROPIC_API_KEY__", config.get("anthropicKey", ""))
        .replace("__WORKSPACE_PATH__", workspace_str)
        .replace("__GATEWAY_TOKEN__", gateway_token)
    )

    config_path.write_text(filled, encoding="utf-8")
    return config_path


# ── Request Handler ──────────────────────────────────────────────
class WizardHandler(http.server.BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        # Suppress noisy access logs; only print errors
        if args and str(args[1]) not in ("200", "204"):
            super().log_message(fmt, *args)

    def _send_json(self, data: dict, status: int = 200):
        body = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def _send_html(self, content: bytes):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)

    def _read_body(self) -> dict:
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length)
        return json.loads(raw.decode("utf-8")) if raw else {}

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        if path in ("/", "/index.html"):
            if WIZARD_HTML.exists():
                self._send_html(WIZARD_HTML.read_bytes())
            else:
                self._send_json({"error": "index.html not found"}, 404)

        elif path == "/api/status":
            self._send_json(get_status())

        else:
            self._send_json({"error": "Not found"}, 404)

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        if path == "/api/save-config":
            try:
                config = self._read_body()

                set_status("configuring", "Writing configuration files...")

                # Validate required field
                if not config.get("anthropicKey", "").strip():
                    self._send_json({"ok": False, "error": "Anthropic API key is required"}, 400)
                    return

                # Ensure workspace exists
                WORKSPACE.mkdir(parents=True, exist_ok=True)

                env_path = write_env_file(config)
                oc_path = write_openclaw_config(config)

                set_status("configured", "Configuration saved")

                self._send_json({
                    "ok": True,
                    "envPath": str(env_path),
                    "openclawConfigPath": str(oc_path),
                })

            except json.JSONDecodeError:
                self._send_json({"ok": False, "error": "Invalid JSON"}, 400)
            except Exception as exc:
                self._send_json({"ok": False, "error": str(exc)}, 500)

        elif path == "/api/complete":
            try:
                WORKSPACE.mkdir(parents=True, exist_ok=True)
                COMPLETE_FLAG.touch()
                set_status("complete", "Setup complete")
                self._send_json({"ok": True})

                # Shut down server after response is flushed
                threading.Thread(target=self._shutdown_server, daemon=True).start()

            except Exception as exc:
                self._send_json({"ok": False, "error": str(exc)}, 500)

        else:
            self._send_json({"error": "Not found"}, 404)

    def _shutdown_server(self):
        import time
        time.sleep(0.5)
        self.server.shutdown()


# ── Main ─────────────────────────────────────────────────────────
def main():
    server = http.server.HTTPServer(("localhost", PORT), WizardHandler)
    print(f"Jarvis Setup Wizard running at http://localhost:{PORT}")
    print("Waiting for configuration...")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    print("Setup wizard server stopped.")


if __name__ == "__main__":
    main()
